# Directories to exclude
exclude-dirs:
  - tick
  
# Files to exclude
exclude-files:
  - README.md
  - .gitignore
  - .pre-commit-config.yaml
  - LICENSE
  - .cent.yaml
  - CODE_OF_CONDUCT.md
  - CONTRIBUTING.md
  - LICENSE.md
  - PULL_REQUEST_TEMPLATE.md
  - README_KR.md
  - TEMPLATES-STATS.md
  - TOP-10.md

# Add github urls
community-templates:
  - https://gist.github.com/0x240x23elu
  - https://gist.github.com/ResistanceIsUseless/e46848f67706a8aa1205c9d2866bff31
  - https://github.com/0XParthJ/Nuclei-Templates
  - https://github.com/0x240x23elu/nuclei2021
  - https://github.com/0x727/FingerprintHub
  - https://github.com/0x727/ObserverWard_0x727
  - https://github.com/0xAwali/Virtual-Host
  - https://github.com/0xPugazh/my-nuclei-templates
  - https://github.com/1in9e/my-nuclei-templates
  - https://github.com/5cr1pt/templates
  - https://github.com/ARPSyndicate/kenzer-templates
  - https://github.com/Aituglo/nuclei-templates
  - https://github.com/Akokonunes/Private-Nuclei-Templates
  - https://github.com/AshiqurEmon/nuclei_templates
  - https://github.com/AshiqurEmon/nuclei_templates.git
  - https://github.com/BeRserKerSec/CVE-2021-26084-Nuclei-template
  - https://github.com/BitTheByte/Monitorizer
  - https://github.com/CharanRayudu/Custom-Nuclei-Templates
  - https://github.com/ChiaraNRTT96/BountySkill
  - https://github.com/Elsfa7-110/mynuclei-templates
  - https://github.com/ExpLangcn/NucleiTP
  - https://github.com/GDSC-IU/automate-with-actions
  - https://github.com/Hardik-Rathod/nuclei-templates
  - https://github.com/Harish4948/Nuclei-Templates
  - https://github.com/HritikThapa7/Top10-Nuclei-Templates-and-Tags
  - https://github.com/JoshMorrison99/url-based-nuclei-templates
  - https://github.com/KeepHowling/all_freaking_nuclei_templates
  - https://github.com/Linuxinet/nuclei-templates
  - https://github.com/MR-pentestGuy/nuclei-templates
  - https://github.com/Mr219/nuclei_templates
  - https://github.com/MrCl0wnLab/Nuclei-Template-Exploit-F5-BIG-IP-iControl-REST-Auth-Bypass-RCE-Command-Parameter
  - https://github.com/Nick2332-dot/ChtandranRayudu_nuclei-templates
  - https://github.com/NightRang3r/misc_nuclei_templates
  - https://github.com/Nithissh0708/Custom-Nuclei-Templates
  - https://github.com/NitinYadav00/My-Nuclei-Templates
  - https://github.com/Odayex/Random-Nuclei-Templates
  - https://github.com/R-s0n/Custom_Vuln_Scan_Templates
  - https://github.com/Saimonkabir/Nuclei-Templates
  - https://github.com/Saptak9983/Nuclei-Template
  - https://github.com/ShangRui-hash/my-nuclei-templates
  - https://github.com/Str1am/my-nuclei-templates
  - https://github.com/System00-Security/backflow
  - https://github.com/Th3eCrow/Nuclei-Templates
  - https://github.com/Ugroon/Nuclei-Templates
  - https://github.com/adampielak/nuclei-templates
  - https://github.com/aels/CVE-2022-37042
  - https://github.com/alexrydzak/rydzak-nuclei-templates
  - https://github.com/applefellow/nuclei_templates_payload_maker
  - https://github.com/arielril/nuclei-templates
  - https://github.com/badboy-sft/badboy_17-Nuclei-Templates-Collection
  - https://github.com/bjhulst/nuclei-custom-templates
  - https://github.com/blazeinfosec/nuclei-templates
  - https://github.com/brinhosa/brinhosa-nuclei-templates
  - https://github.com/bu1xuan2/Nuclei-Templateser
  - https://github.com/bufferbandit/gitScanNucleiTemplate
  - https://github.com/c-sh0/nuclei_templates
  - https://github.com/c0rv4x/scanfactory-nuclei-templates
  - https://github.com/c3l3si4n/malicious_nuclei_templates
  - https://github.com/clarkvoss/Nuclei-Templates
  - https://github.com/d3sca/Nuclei_Templates
  - https://github.com/daffainfo/my-nuclei-templates
  - https://github.com/daffainfo/nuclei-templates
  - https://github.com/danielmofer/nuclei_templates
  - https://github.com/dk4trin/templates-nuclei
  - https://github.com/dwisiswant0/nuclei-templates
  - https://github.com/dwisiswant0/nuclei-templates-dir
  - https://github.com/ekinsb/Nuclei-Templates
  - https://github.com/emadshanab/Nuclei-Templates-Collection
  - https://github.com/emadshanab/nuclei-templates
  - https://github.com/emadshanab/nucleiDB
  - https://github.com/esetal/nuclei-bb-templates
  - https://github.com/ethicalhackingplayground/erebus
  - https://github.com/ethicalhackingplayground/erebus-templates
  - https://github.com/foulenzer/foulenzer-templates
  - https://github.com/geeknik/nuclei-template-generator
  - https://github.com/geeknik/nuclei-templates
  - https://github.com/geeknik/nuclei-templates-1
  - https://github.com/geeknik/the-nuclei-templates
  - https://github.com/glyptho/templatesallnuclei
  - https://github.com/gy741/nuclei-templates
  - https://github.com/iamthefrogy/nerdbug
  - https://github.com/im403/nuclei-temp
  - https://github.com/javaongsan/nuclei-templates
  - https://github.com/jbertman/generate-nuclei-templates
  - https://github.com/jenkinsci/nuclei-plugin
  - https://github.com/joanbono/nuclei-templates
  - https://github.com/justmumu/SpringShell
  - https://github.com/kab33r/nuclei-templates
  - https://github.com/kabilan1290/templates
  - https://github.com/kankburhan/gampung
  - https://github.com/kh4sh3i/CVE-2022-23131
  - https://github.com/letfornz/all-nuclei-templates
  - https://github.com/lliwi/nuclei-repo-hunter
  - https://github.com/manasmbellani/nuclei-templates
  - https://github.com/marcositu/nuclei-custom-templates
  - https://github.com/medbsq/ncl
  - https://github.com/meme-lord/Custom-Nuclei-Templates
  - https://github.com/mtuxpe/Sipeed_Template
  - https://github.com/n1f2c3/mytemplates
  - https://github.com/narasimha5x5/nuclei-templates
  - https://github.com/nirajdhalani/nuclei_templates_collection
  - https://github.com/notnotnotveg/nuclei-custom-templates
  - https://github.com/obreinx/nuceli-templates
  - https://github.com/optiv/mobile-nuclei-templates
  - https://github.com/osintbrazuca/nuclei-templates-brazuca
  - https://github.com/p3n73st3r/Nuclei-Templates
  - https://github.com/pacho15/mynuclei_templates
  - https://github.com/panch0r3d/nuclei-templates
  - https://github.com/peanuth8r/Nuclei_Templates
  - https://github.com/pentest-dev/Profesional-Nuclei-Templates
  - https://github.com/pikpikcu/my-nuclei-templates
  - https://github.com/pikpikcu/nuclei-templates
  - https://github.com/ping-0day/templates
  - https://github.com/pownjs/nucleoid
  - https://github.com/praetorian-inc/chariot-launch-nuclei-templates
  - https://github.com/prasant-paudel/nuclipy
  - https://github.com/projectdiscovery/network-fingerprint
  - https://github.com/projectdiscovery/nuclei-templates
  - https://github.com/projectdiscovery/nuclei-templates.git
  - https://github.com/projectdiscovery/templates-stats
  - https://github.com/pussycat0x/nuclei-templates
  - https://github.com/rafaelcaria/Nuclei-Templates
  - https://github.com/rafaelwdornelas/my-nuclei-templates
  - https://github.com/rahulkadavil/nuclei-templates
  - https://github.com/randomstr1ng/nuclei-sap-templates
  - https://github.com/redteambrasil/nuclei-templates
  - https://github.com/ree4pwn/my-nuclei-templates
  - https://github.com/reewardius/nuclei-templates-new
  - https://github.com/reewardius/nuclei_templates_new
  - https://github.com/riskscanner/riskscanner
  - https://github.com/rix4uni/nuclei-templates-threader
  - https://github.com/sadnansakin/my-nuclei-templates
  - https://github.com/securitytest3r/nuclei_templates_work
  - https://github.com/sharathkramadas/k8s-nuclei-templates
  - https://github.com/shifa123/detections
  - https://github.com/shifa123/nuclei-templates-all
  - https://github.com/sickwell/nuclei-templates
  - https://github.com/smaranchand/nuclei-templates
  - https://github.com/sobinge/nuclei-templates
  - https://github.com/souzomain/mytemplates
  - https://github.com/souzomain/souzo-templates
  - https://github.com/sudo-jtcsec/public-nuclei-templates
  - https://github.com/sushant-kamble/mynuclei-template
  - https://github.com/tamimhasan404/Open-Source-Nuclei-Templates-Downloader
  - https://github.com/tedmdelacruz/custom-nuclei-templates
  - https://github.com/test502git/log4j-fuzz-head-poc
  - https://github.com/th3r4id/nuclei-templates
  - https://github.com/thebrnwal/Content-Injection-Nuclei-Script
  - https://github.com/thelabda/labdanuclei
  - https://github.com/thelabda/nuclei-templates
  - https://github.com/themastersunil/Nuclei-TamplatesBackup.git
  - https://github.com/themastersunil/nucleiDB
  - https://github.com/toramanemre/apache-solr-log4j-CVE-2021-44228
  - https://github.com/toramanemre/log4j-rce-detect-waf-bypass
  - https://github.com/trickest/log4j
  - https://github.com/trungkay2/Nuclei-template
  - https://github.com/twseptian/custom-nuclei-templates
  - https://github.com/wasp76b/nuclei-templates
  - https://github.com/wr00t/templates
  - https://github.com/xfiftyone/redteam-tpls
  - https://github.com/xm1k3/cent
  - https://github.com/yavolo/nuclei-templates
  - https://github.com/z3bd/nuclei-templates
  - https://github.com/zinminphyo0/KozinTemplates
